### ISSUE TITLE
Convenient access to data

### ISSUE THREAD

**Issue by shaman-narayanasamy** [simroux/VirSorter#8]
Hi!

I have a small request. I've been trying to download the databse for VirSorter, but to no avail. The problem seems to be the size limit set by the service provider (CyVerse) for the download which prevents a regular download and suggests me to use some specialized software for download. I am having a hard time downloading it via the suggested method. I am not sure if it is due to my institutional firewall issue or I am using the software wrongly. 

Is it possible for you to upload the data on an archiving platform such as Zenodo (https://zenodo.org/)? The cool thing is that you also get a DOI assigned to your upload and therefore can be cited.

I'm not sure if you are aware of this limitation, or if you have a specific reason for depositing it on that particular platform but, I would really appreciate your help :)

Best regards,
Shaman

**Comment by simroux** [comment]
Hi Shaman,

We would rather keep the data in a single place, both because it allows us to update these data when needed (and avoid multiple versions of the data to circulate at the same time), and because the publication include the link to CyVerse (where the data are currently stored).

However, there should not be any size limit in CyVerse, and you should be able to use direct download through the datacommons portal (http://datacommons.cyverse.org/browse/iplant/home/shared/imicrobe/VirSorter), or use Cyberduck (https://pods.iplantcollaborative.org/wiki/display/DS/Using+Cyberduck+for+Uploading+and+Downloading+to+the+Data+Store) and / or icommands (https://pods.iplantcollaborative.org/wiki/display/DS/Using+iCommands) to download outside of a web browser.
Did these 3 methods fail for you ?

Best,

Simon

**Comment by shaman-narayanasamy** [comment]
Hi Simon,

Thanks for the fast reply. I totally understand your point about centralizing the data in a single location. 

I actually tried four methods to get it. 

1. Direct download where I get [this](http://datacommons.cyverse.org/browse/iplant/home/shared/imicrobe/VirSorter/virsorter-data.tar.gz). 

2. I follow the instructions and registered to CyVerse, hoping it would be easier. However, when I actually download it, I get a 1.1GB file which is apparently corrupted. I'm guessing it is not the full file as it should be ~3.7GB. There is no indication that the download is interupted.

3. Cyberduck. No can do. Using a Linux system.

4. iCommands and iDrop desktop failed. I followed the precise in the link you provided awhile back. I tried again after your replied. Here is what I did and the error I got:
```
$ iinit 
One or more fields in your iRODS environment file (.irodsEnv) are
missing; please enter them.
Enter the host name (DNS) of the server to connect to:data.iplantcollaborative.org
Enter the port number:1247
Enter your irods user name:
Enter your irods zone:
Those values will be added to your environment file (for use by
other i-commands) if the login succeeds.

Enter your current iRODS password:
ERROR: _rcConnect: connectToRhost error, server on data.iplantcollaborative.org is probably down status = -347000 USER_SOCK_CONNECT_TIMEDOUT
ERROR: Saved password, but failed to connect to server data.iplantcollaborative.org
```
Similar error with iDrop...

Maybe I am not doing it right. Let me know if there is any way we can work around this issue. Sorry I posted it over here. I wasn't sure if it is the right place. Looking forward to your reply.

Cheers,
Shaman

**Comment by simroux** [comment]
Hi Shaman,

I was somewhat hoping you did not already try all this ... :-) 

Anyway, the icommands method should work, so it might be a CyVerse issue. It might be worth asking them directly on their forum (http://ask.iplantcollaborative.org/questions/, usually they are very responsive). 
 The two things I can think of are trying to use icommands with the "anonymous" user name (and no passwrod), and try it outside of your office (apparently someone had the same issue: http://ask.iplantcollaborative.org/question/5144/cant-login-with-icommands/ and it was because of an institutional firewall).

Let me know if you still don't achieve to get any of these methods working, in which case I will set up an alternative private repository for these data.

Cheers,

Simon

**Comment by shaman-narayanasamy** [comment]
Hi Simon,

Yes, I probably should have posed this issue to the right channel. Sorry to have taken your time for such a trivial matter.

On another note, it downloads just fine in my home network. Damn these institutional restrictions... Thanks a lot for the help :)

I shall close the issue now.

Best,
Shaman

**Comment by simroux** [comment]
Happy to know that it is now solved :-)

Best,

Simon
