### ISSUE TITLE
Multiple assembly files

### ISSUE THREAD

**Issue by DeaconOfBiology** [simroux/VirSorter#80]
I was wondering if I could run virsorter on mulitple assembly files without it over writing the files with each iteration? For example I have 24 .fa files representing assemblies from 24 different samples. When runing virsorter, can I in put '-f *.fa' and have it run through all the assembly files, or should I do this with a for loop? Thanks for any advice

**Comment by simroux** [comment]
Hi,
A wildcard in the argument will likely not work, your options are either to combined the 24 .fa files in a single file, that would then be provided as input fasta, or to run this with a for loop. I would suggest the latter, since that will speed things up considerably if you can run these different VirSorter runs in parallel. 

Also it may be worth pointing out that we just release a beta version of VirSorter2 (https://github.com/jiarong/VirSorter2) which, depending on your data and analysis, may be better suited than VirSorter.

Best,
Simon

**Comment by DeaconOfBiology** [comment]
Hey Simon,
Yes sir, I have already downloaded VirSorter2 and love it. However I found that it does not create a affi-contigs.tab file in the output, which I need for another program called DRAM-v. But, Jiarong  informed me that it should be included in a later edition in the coming weeks. So, in the mean time, I am testing DRAM by using the legacy VirSorter.

**Comment by simroux** [comment]
Sounds like a good plan :-)
